name=ALEX80micro
version=1.0.0
author=Flavio Carchedi, Paolo Godino
maintainer=Paolo Godino
sentence=Alex80 micro Shield Library
paragraph=The ALEX80micro Arduino Library simplifies the development of applications for the ALEX80µ educational computer. It provides functions for memory access, bus control and communication with the Z80-based system through an easy-to-use Arduino API.
category=Other
url=https://alexa-academy.it/
architectures=*
