#!/usr/bin/env python3
"""Assemble ALEX80 MS BASIC and generate the Arduino PROGMEM array.

This file lives in the private, git-ignored ``basic`` directory.
It requires z88dk-z80asm, either in PATH or in ~/z88dk/bin.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


ROM_SIZE = 0x2000
FILL_BYTE = 0x00
MODULES = (
    ("int_alex80u.asm", 0x0000),
    ("basic.asm", 0x0150),
)

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
DEFAULT_OUTPUT = SCRIPT_DIR / "intROM.generated.txt"
SKETCH = PROJECT_DIR / "examples" / "Alex80u_MS_BASIC" / "Alex80u_MS_BASIC.ino"

ARRAY_RE = re.compile(
    r"const\s+PROGMEM\s+byte\s+intROM(?:\s*\[[^\]]*\])?\s*=\s*\{"
    r"(?P<body>.*?)"
    r"\};",
    re.DOTALL,
)
BYTE_RE = re.compile(r"0x([0-9A-Fa-f]{2})")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Assemble int_alex80u.asm and basic.asm, merge them into an "
            "8 KiB ROM and generate the intROM PROGMEM declaration."
        )
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"generated text file (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--assembler",
        type=Path,
        help="path to z88dk-z80asm (otherwise searched automatically)",
    )
    return parser.parse_args()


def find_assembler(explicit: Path | None) -> Path:
    if explicit is not None:
        candidate = explicit.expanduser().resolve()
        if candidate.is_file():
            return candidate
        raise RuntimeError(f"assembler not found: {candidate}")

    in_path = shutil.which("z88dk-z80asm")
    if in_path:
        return Path(in_path).resolve()

    home_install = Path.home() / "z88dk" / "bin" / "z88dk-z80asm"
    if home_install.is_file():
        return home_install.resolve()

    raise RuntimeError(
        "z88dk-z80asm not found; install z88dk or pass "
        "--assembler /path/to/z88dk-z80asm"
    )


def assemble_module(
    assembler: Path,
    source_name: str,
    build_dir: Path,
) -> bytes:
    source = SCRIPT_DIR / source_name
    if not source.is_file():
        raise RuntimeError(f"source not found: {source}")

    output_name = f"{source.stem}.bin"
    command = [
        str(assembler),
        "-b",
        f"-O={build_dir}",
        f"-o={output_name}",
        str(source),
    ]
    result = subprocess.run(command, text=True, capture_output=True)
    if result.returncode != 0:
        details = "\n".join(
            part.strip() for part in (result.stdout, result.stderr) if part.strip()
        )
        raise RuntimeError(f"assembly failed for {source_name}:\n{details}")

    output = build_dir / output_name
    if not output.is_file():
        raise RuntimeError(f"assembler did not create: {output}")
    return output.read_bytes()


def build_rom(assembler: Path) -> tuple[bytes, list[tuple[str, int, int]]]:
    rom = bytearray([FILL_BYTE]) * ROM_SIZE
    ranges: list[tuple[int, int, str]] = []
    report: list[tuple[str, int, int]] = []

    with tempfile.TemporaryDirectory(prefix="alex80-basic-") as temporary:
        build_dir = Path(temporary)
        for source_name, origin in MODULES:
            binary = assemble_module(assembler, source_name, build_dir)
            end = origin + len(binary)

            if end > ROM_SIZE:
                raise RuntimeError(
                    f"{source_name} ends at 0x{end - 1:04X}, beyond "
                    f"the ROM limit 0x{ROM_SIZE - 1:04X}"
                )

            for other_start, other_end, other_name in ranges:
                if origin < other_end and end > other_start:
                    raise RuntimeError(
                        f"{source_name} [0x{origin:04X}, 0x{end - 1:04X}] "
                        f"overlaps {other_name} "
                        f"[0x{other_start:04X}, 0x{other_end - 1:04X}]"
                    )

            rom[origin:end] = binary
            ranges.append((origin, end, source_name))
            report.append((source_name, origin, len(binary)))

    return bytes(rom), report


def format_array(rom: bytes) -> str:
    lines = [
        "// Generated by basic/build_rom.py; do not edit byte values manually.",
        "const PROGMEM byte intROM[] = {",
    ]
    for offset in range(0, len(rom), 16):
        chunk = rom[offset : offset + 16]
        suffix = "," if offset + len(chunk) < len(rom) else ""
        lines.append("  " + ", ".join(f"0x{byte:02X}" for byte in chunk) + suffix)
    lines.append("};")
    return "\n".join(lines) + "\n"


def read_sketch_rom() -> bytes | None:
    if not SKETCH.is_file():
        return None
    match = ARRAY_RE.search(SKETCH.read_text(encoding="utf-8"))
    if match is None:
        return None
    return bytes(int(value, 16) for value in BYTE_RE.findall(match.group("body")))


def main() -> int:
    args = parse_args()
    try:
        assembler = find_assembler(args.assembler)
        rom, modules = build_rom(assembler)

        output = args.output.expanduser()
        if not output.is_absolute():
            output = (Path.cwd() / output).resolve()
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(format_array(rom), encoding="utf-8")

        digest = hashlib.sha256(rom).hexdigest()
        print(f"Assembler: {assembler}")
        for name, origin, size in modules:
            print(
                f"{name}: {size} bytes, "
                f"0x{origin:04X}-0x{origin + size - 1:04X}"
            )
        print(f"ROM: {len(rom)} bytes")
        print(f"SHA-256: {digest}")
        print(f"Generated: {output}")

        current = read_sketch_rom()
        if current is None:
            print("Sketch comparison: intROM not found")
        elif current == rom:
            print("Sketch comparison: identical")
        else:
            common = min(len(current), len(rom))
            differences = sum(
                current[index] != rom[index] for index in range(common)
            ) + abs(len(current) - len(rom))
            print(
                f"Sketch comparison: different "
                f"({differences} byte positions, sketch size {len(current)})"
            )
        return 0
    except (OSError, RuntimeError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
